name: iProfessions
main: com.ptibiscuit.iprofession.Plugin
version: 1.9.1
depend: [PluginsBaker]
softepend: [BeardStat]
authors:
- Ptibiscuit
commands:
  plearn:
    description: Usefull to learn a profession.
    usage: /plearn <Profession>
  pforget:
    description: Forget your profession.
    usage: /pforget <Profession>
  premprofuser:
    description: Remove a profession to a user.
    usage: /premprofuser <Player> <Profession>
  paddprofuser:
    description: Add a profession to a user.
    usage: /paddprofuser <Player> <Profession>
  pwhois:
    description: Set a profession to a player
    usage: /pwhois [Player]